test:
  clients:
    default:
      database: playground_test
      hosts:
        - localhost:27017

development:
  clients:
    default:
      database: playground_dev
      hosts:
        - localhost:27017